//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntarRepo.Properties
{

    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string folder
        {
            get
            {
                return ((string)(this["folder"]));
            }
            set
            {
                this["folder"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string wynik
        {
            get
            {
                return ((string)(this["wynik"]));
            }
            set
            {
                this["wynik"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string filtr
        {
            get
            {
                return ((string)(this["filtr"]));
            }
            set
            {
                this["filtr"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string katalogRoboczy
        {
            get
            {
                if (this["katalogRoboczy"] == null || ((string)(this["katalogRoboczy"])).Length == 0)
                    return Program.Configuration.GetSection("KatalogRoboczy").Value;
                else
                    return ((string)(this["katalogRoboczy"]));
            }
            set
            {
                this["katalogRoboczy"] = value;
            }
        }
    }
}
